*mikesamuel/fix-bug-249-isRegexp@1337 | mikesamuel | 2008-05-09 16:44:19 -0800 (Fri, 09 May 2008)
Description:

Issue 249 : JsLexer.isRegexp problem

<script>
a = min / max;
</script>

FATAL_ERROR: a1.html:2+9 - 3+1: Unclosed string

1, the error message is a little confusing, it's an unclosed regexp, not an
unclosed string.

2, the js lexer thinks the / is a regexp, because JsLexer.isRegexp is
checking if the previous token is a keyword using find() instead of
matches().  so 'min' matches the pattern, because 'in' is a keyword.






git-svn-id: https://google-caja.googlecode.com/svn/trunk@1338 360991c0-9f3b-0410-ba87-8b362a00edf4