Issue 9675  http://codereview.appspot.com/9675 Fix bug 930: Error cajoling empty or trivial files.
What steps will reproduce the problem?
    1. Create an empty JS file; or, e.g. a file with only comments.
    2. Cajole either through the shell using bin/cajole_html or 
       programmatically via the PluginCompiler class.
    3. Inspect error:

    ERROR: Unexpected end of input in <file>.js

I don't want to modify the parsers since they are constrained by
what is a valid production, and many existing uses assume that
they will error on empty inputs.

Modified PluginCompilerMain to treat empty inputs as no input at all.

metaweta@gmail.com


git-svn-id: https://google-caja.googlecode.com/svn/trunk@3041 360991c0-9f3b-0410-ba87-8b362a00edf4